### ISSUE TITLE
Very far behind on work

### ISSUE THREAD

**Issue by salamander2** [Java-prog-class-2019/TextAdv2#4]
# This team is really far behind on working on this project.  

There are only 3 commits, all of them by Carter. The program will now compile but doesn't even print something when it runs.  Nothing is happening at all. In class all week, you guys have been mostly doing other stuff, not working on this project and you're now way behind. 

What are your plans? Do you all just hope that someone else will get things working? Do you investigate what exactly the holdup/bottleneck is when nothing is being done? There are three people here who all need to take a whole lot more initiative and responsibility for this project.  If it were a company, you'd probably be fired.

**Comment by jenelos** [comment]
Mr. Harwood there were far more than 3 commits, probably around 30, and these were then copied by Carter and repushed because we had to stop using gradle. The game now runs, and once rooms start working the game should seem far better. Rooms are nearing completion as far as I know, the player class just needs movement to be finished up, which it nearly is at this point. As for combat, I have an idea for it that cannot be implemented until Rooms are finished.

**Comment by salamander2** [comment]
#SUPER
